   drop_user: "DROP TABLE IF EXISTS users;"
   drop_restaurants: "DROP TABLE IF EXISTS restaurants;"
   create_user: "CREATE TABLE users (id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT, lastname TEXT, password TEXT, email TEXT, phone TEXT);"
   create_restaurants: "CREATE TABLE restaurants (id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT, type TEXT, keys TEXT, average_price INTEGER, user_id INTEGER);"
   insert_user: "INSERT INTO users (name, lastname, password, email, phone) VALUES (?, ?, ?, ?, ?);"
   insert_restaurant: "INSERT INTO restaurants (name, type, keys, average_price, user_id) VALUES (?, ?, ?, ?, ?);"
   select_users: "SELECT * FROM users;"
   select_restaurants: "SELECT * FROM restaurants;"
   select_join: "SELECT u.id as user_id, u.name as user_name, u.lastname as user_lastname, r.id as restaurant_id, r.name as restaurant_name, r.type, r.average_price FROM users u JOIN restaurants r ON u.id = r.user_id;"
